name: module3_task1

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task1:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Setup
        run: cd module3_task1 && sudo ./setup.sh

      - name: Make Build
        # Change help to build and install necessary dependencies to work
        run: cd module3_task1 && make help
