name: module3_task 0
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        #uses: actions/checkout@v2#
        run: |
          cd module3_task0
          make helps

      - name: Validate Makefile
        run: |
          cd module3_task0
          make help
